# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gif-game' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gif-game

  target 'gif-gameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gif-gameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
